services:
  db_host:
    container_name: db
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - "$PWD/db_data:/var/lib/mysql"
    networks:
      - net
  remote_host:
    container_name: remote-host
    image: remote-host
    build:
      context: remote-host
    networks:
      - net
    depends_on:
      - db_host
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - $PWD/jenkins_home:/var/jenkins_home
    networks:
      - net
    depends_on:
      - remote_host
networks:
  net:
